/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-20 19:34:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bean.employee;
import com.dao.empdao;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.bean.employee");
    _jspx_imports_classes.add("com.dao.empdao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- CSS only -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\r\n");
      out.write("<!-- JavaScript Bundle with Popper -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function checkfname() \r\n");
      out.write("	{\r\n");
      out.write("		var f = document.myform.fname.value;\r\n");
      out.write("		\r\n");
      out.write("		var reg = /^[a-zA-Z]+$/;\r\n");
      out.write("		\r\n");
      out.write("		if(f==\"\")\r\n");
      out.write("			{\r\n");
      out.write("			document.getElementById(\"fname\").innerHTML=\"please enter first name\";\r\n");
      out.write("			}\r\n");
      out.write("		else if(!reg.test(f))\r\n");
      out.write("			{\r\n");
      out.write("			document.getElementById(\"fname\").innerHTML=\"only character\";\r\n");
      out.write("			}\r\n");
      out.write("		else\r\n");
      out.write("			{\r\n");
      out.write("			document.getELementById(\"fname\").innerHTML=\"\";\r\n");
      out.write("			}\r\n");
      out.write("	}\r\n");
      out.write("	function checkmobile() \r\n");
      out.write("	{\r\n");
      out.write("		var m = document.myform.mobile.value;\r\n");
      out.write("		\r\n");
      out.write("		var reg = /^\\d{10}$/;\r\n");
      out.write("		\r\n");
      out.write("		if(m==\"\")\r\n");
      out.write("			{\r\n");
      out.write("			document.getElementById(\"mobile\").innerHTML=\"please enter mobile numer\";\r\n");
      out.write("			}\r\n");
      out.write("		else if(!reg.test(m))\r\n");
      out.write("			{\r\n");
      out.write("			document.getElementById(\"mobile\").innerHTML=\"enter  number\";\r\n");
      out.write("			}\r\n");
      out.write("		else\r\n");
      out.write("			{\r\n");
      out.write("			document.getELementById(\"mobile\").innerHTML=\"\";\r\n");
      out.write("			}\r\n");
      out.write("	}\r\n");
      out.write("	function checkemail() \r\n");
      out.write("	{\r\n");
      out.write("		var e = document.myform.email.value;\r\n");
      out.write("		\r\n");
      out.write("		var reg = /^[A-Za-z0-9._-]+@[a-zA-Z]+\\.[a-zA-Z]{2,4}$/;\r\n");
      out.write("		\r\n");
      out.write("		if(e==\"\")\r\n");
      out.write("			{\r\n");
      out.write("			document.getElementById(\"email\").innerHTML=\"please enter email address\";\r\n");
      out.write("			}\r\n");
      out.write("		else if(!reg.test(e))\r\n");
      out.write("			{\r\n");
      out.write("			document.getElementById(\"email\").innerHTML=\"enter valid address\";\r\n");
      out.write("			}\r\n");
      out.write("		else\r\n");
      out.write("			{\r\n");
      out.write("			document.getELementById(\"email\").innerHTML=\"\";\r\n");
      out.write("			}\r\n");
      out.write("	}\r\n");
      out.write("	function checkpsw() \r\n");
      out.write("	{\r\n");
      out.write("		var p = document.myform.psw.value;\r\n");
      out.write("		\r\n");
      out.write("		var reg = /^(?=.*\\d)+(?=.*[a-z])+(?=.*[A-Z])+(?=.*[^a-zA-Z0-9])+(?!.*\\s).{8,15}$/;\r\n");
      out.write("		\r\n");
      out.write("		if(p==\"\")\r\n");
      out.write("			{\r\n");
      out.write("			document.getElementById(\"psw\").innerHTML=\"enter password\";\r\n");
      out.write("			}\r\n");
      out.write("		else if(!reg.test(p))\r\n");
      out.write("			{\r\n");
      out.write("			document.getElementById(\"psw\").innerHTML=\"ABCabc@123\";\r\n");
      out.write("			}\r\n");
      out.write("		else\r\n");
      out.write("			{\r\n");
      out.write("			document.getELementById(\"psw\").innerHTML=\"\";\r\n");
      out.write("			}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	employee e = (employee)request.getAttribute("emp"); 

      out.write("\r\n");
      out.write("<form name=\"myform\" method=\"post\" action=\"empcontroller\">\r\n");
      out.write("	<table align=\"center\">\r\n");
      out.write("	<h1 align=\"center\">update Form</h1>\r\n");
      out.write("				<input type=\"hidden\" name=\"id\" value=\"");
      out.print(e.getId());
      out.write("\">\r\n");
      out.write("		<tr>\r\n");
      out.write("\r\n");
      out.write("			<td>First Name</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"fname\" onblur=\"checkfname();\" value=\"");
      out.print(e.getFname());
      out.write("\"></td>\r\n");
      out.write("			<td><span id=\"fname\"></span></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("		");

			if(e.getGender().equals("male"))
			{
		
      out.write("\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"radio\" name=\"gender\" value=\"male\" checked =\"checked\">Male\r\n");
      out.write("				<input type=\"radio\" name=\"gender\" value=\"Female\">Female\r\n");
      out.write("			</td>	\r\n");
      out.write("		");
 		
			}
			else if(e.getGender().equals("female"))
			{
		
      out.write("\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"radio\" name=\"gender\" value=\"male\">Male\r\n");
      out.write("				<input type=\"radio\" name=\"gender\" value=\"Female\" checked=\"checked\">Female	\r\n");
      out.write("			</td>	\r\n");
      out.write("		");
 		
			}
			else
			{
		
      out.write("\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"radio\" name=\"gender\" value=\"male\">Male\r\n");
      out.write("				<input type=\"radio\" name=\"gender\" value=\"Female\">Female	\r\n");
      out.write("			</td>\r\n");
      out.write("		");
 		
			}
		
      out.write("\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>Mobile Number</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"mobile\" onblur=\"checkmobile();\" value=\"");
      out.print(e.getMobile());
      out.write("\"></td>\r\n");
      out.write("			<td><span id=\"mobile\"></span></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>Email</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"email\" onblur=\"checkemail();\" value=\"");
      out.print(e.getEmail() );
      out.write("\"></td>\r\n");
      out.write("			<td><span id=\"email\"></span></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>Password</td>\r\n");
      out.write("			<td><input type=\"password\" name=\"psw\" onblur=\"checkpsw();\" value=\"");
      out.print(e.getPassword());
      out.write("\"></td>\r\n");
      out.write("			<td><span id=\"psw\"></span></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><input type=\"submit\" name=\"action\" value=\"update\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
